# -*- coding: utf-8 -*-
"""
Espressioni cinesi per Jewel.
Ogni voce contiene:
- pinyin: trascrizione ufficiale con i toni
- pronuncia: guida fonetica "all'italiana" per leggerla facilmente
- significato: traduzione in italiano
- esempio: una frase o nota d'uso
"""

EXPRESSIONS = [
    {
        "pinyin": "Nǐ hǎo",
        "pronuncia": "nii hao (toni: 3-3, la prima sillaba diventa di fatto un secondo tono)",
        "significato": "Ciao / Salve",
        "esempio": "Saluto base, si usa in qualunque momento del giorno.",
    },
    {
        "pinyin": "Nǐ hǎo ma?",
        "pronuncia": "nii hao ma?",
        "significato": "Come stai?",
        "esempio": "Risposta classica: 'Wǒ hěn hǎo' (sto molto bene).",
    },
    {
        "pinyin": "Xièxie",
        "pronuncia": "scié-scie (la 'x' si legge come 'sc' di 'scena')",
        "significato": "Grazie",
        "esempio": "Per ringraziare in modo educato.",
    },
    {
        "pinyin": "Bú kèqi",
        "pronuncia": "bu kè-ci (la 'q' si legge come 'ci' di 'cinema')",
        "significato": "Prego / Di niente",
        "esempio": "Risposta naturale dopo un 'xièxie'.",
    },
    {
        "pinyin": "Duìbuqǐ",
        "pronuncia": "duéi-bu-cii",
        "significato": "Scusami / Mi dispiace",
        "esempio": "Per scusarsi sinceramente.",
    },
    {
        "pinyin": "Méi guānxi",
        "pronuncia": "méi guan-sci",
        "significato": "Non importa / Nessun problema",
        "esempio": "Risposta a una scusa.",
    },
    {
        "pinyin": "Zàijiàn",
        "pronuncia": "zài-gièn (la 'z' è una 'ds' dolce)",
        "significato": "Arrivederci",
        "esempio": "Letteralmente: 'ci rivediamo'.",
    },
    {
        "pinyin": "Wǒ ài nǐ",
        "pronuncia": "uò ài nii",
        "significato": "Ti amo",
        "esempio": "Da dire a chi ti fa battere il cuore.",
    },
    {
        "pinyin": "Wǒ xǐhuan nǐ",
        "pronuncia": "uò sci-huan nii",
        "significato": "Mi piaci",
        "esempio": "Un gradino prima di 'wǒ ài nǐ'.",
    },
    {
        "pinyin": "Nǐ jiào shénme míngzi?",
        "pronuncia": "nii giào scen-me ming-zi",
        "significato": "Come ti chiami?",
        "esempio": "Domanda classica per fare conoscenza.",
    },
    {
        "pinyin": "Wǒ jiào Jewel",
        "pronuncia": "uò giào Jewel",
        "significato": "Mi chiamo Jewel",
        "esempio": "Risposta perfetta per te.",
    },
    {
        "pinyin": "Hěn gāoxìng rènshi nǐ",
        "pronuncia": "hen gao-scìng ren-sci nii",
        "significato": "Piacere di conoscerti",
        "esempio": "Si dice quando ci si presenta.",
    },
    {
        "pinyin": "Nǐ shì nǎ guó rén?",
        "pronuncia": "nii sci nà guo ren",
        "significato": "Di che paese sei?",
        "esempio": "Letteralmente: 'tu sei di quale paese persona?'.",
    },
    {
        "pinyin": "Wǒ shì Yìdàlì rén",
        "pronuncia": "uò sci ì-dà-lì ren",
        "significato": "Sono italiano/a",
        "esempio": "Yìdàlì = Italia.",
    },
    {
        "pinyin": "Nǐ huì shuō Yīngyǔ ma?",
        "pronuncia": "nii huéi sciuo ing-iü ma",
        "significato": "Parli inglese?",
        "esempio": "Utilissima se ti perdi.",
    },
    {
        "pinyin": "Wǒ bù dǒng",
        "pronuncia": "uò bu dong",
        "significato": "Non capisco",
        "esempio": "Da tenere sempre nel taschino.",
    },
    {
        "pinyin": "Qǐng zài shuō yí biàn",
        "pronuncia": "cing zài sciuo i bièn",
        "significato": "Per favore, ripeti",
        "esempio": "Quando il cinese va troppo veloce.",
    },
    {
        "pinyin": "Màn yìdiǎn",
        "pronuncia": "man i-dièn",
        "significato": "Più lentamente",
        "esempio": "Salvavita nelle conversazioni vere.",
    },
    {
        "pinyin": "Wǒ è le",
        "pronuncia": "uò è le",
        "significato": "Ho fame",
        "esempio": "Il '-le' indica un cambio di stato.",
    },
    {
        "pinyin": "Wǒ kě le",
        "pronuncia": "uò kè le",
        "significato": "Ho sete",
        "esempio": "Stessa struttura di 'wǒ è le'.",
    },
    {
        "pinyin": "Hǎo chī",
        "pronuncia": "hao ci",
        "significato": "Buono (di cibo) / Delizioso",
        "esempio": "Letteralmente: 'buono da mangiare'.",
    },
    {
        "pinyin": "Hǎo hē",
        "pronuncia": "hao he",
        "significato": "Buono (di bevanda)",
        "esempio": "Letteralmente: 'buono da bere'.",
    },
    {
        "pinyin": "Wǒ yào zhège",
        "pronuncia": "uò iào gè-ghe",
        "significato": "Voglio questo",
        "esempio": "Comodissimo al ristorante o al mercato.",
    },
    {
        "pinyin": "Duōshǎo qián?",
        "pronuncia": "duo-scào cièn",
        "significato": "Quanto costa?",
        "esempio": "Domanda d'oro nei negozi.",
    },
    {
        "pinyin": "Tài guì le",
        "pronuncia": "tài guéi le",
        "significato": "È troppo caro",
        "esempio": "Inizio della contrattazione.",
    },
    {
        "pinyin": "Piányi yìdiǎn",
        "pronuncia": "pien-i i-dièn",
        "significato": "Un po' più economico",
        "esempio": "Per contrattare il prezzo.",
    },
    {
        "pinyin": "Wǒ mǎi",
        "pronuncia": "uò mai",
        "significato": "Lo compro",
        "esempio": "Per chiudere la trattativa.",
    },
    {
        "pinyin": "Cèsuǒ zài nǎr?",
        "pronuncia": "tzè-suo zai nar",
        "significato": "Dov'è il bagno?",
        "esempio": "Una delle frasi più utili al mondo.",
    },
    {
        "pinyin": "Zhège shì shénme?",
        "pronuncia": "gè-ghe sci scen-me",
        "significato": "Cos'è questo?",
        "esempio": "Quando incontri qualcosa di misterioso.",
    },
    {
        "pinyin": "Wǒ lèi le",
        "pronuncia": "uò léi le",
        "significato": "Sono stanco/a",
        "esempio": "Dopo una lunga giornata.",
    },
    {
        "pinyin": "Wǒ kùn le",
        "pronuncia": "uò kuen le",
        "significato": "Ho sonno",
        "esempio": "Prima di andare a letto.",
    },
    {
        "pinyin": "Wǎn'ān",
        "pronuncia": "uan-an",
        "significato": "Buonanotte",
        "esempio": "L'ultimo saluto della giornata.",
    },
    {
        "pinyin": "Zǎo'ān",
        "pronuncia": "zao-an",
        "significato": "Buongiorno (al mattino)",
        "esempio": "Letteralmente: 'pace mattutina'.",
    },
    {
        "pinyin": "Wǎnshàng hǎo",
        "pronuncia": "uan-sciàng hao",
        "significato": "Buonasera",
        "esempio": "Letteralmente: 'sera buona'.",
    },
    {
        "pinyin": "Jīntiān tiānqì hěn hǎo",
        "pronuncia": "ghin-tien tien-ci hen hao",
        "significato": "Oggi c'è bel tempo",
        "esempio": "Per rompere il ghiaccio.",
    },
    {
        "pinyin": "Xià yǔ le",
        "pronuncia": "scià iü le",
        "significato": "Sta piovendo",
        "esempio": "Letteralmente: 'è caduta pioggia'.",
    },
    {
        "pinyin": "Hěn rè",
        "pronuncia": "hen re",
        "significato": "Fa molto caldo",
        "esempio": "Tipica estate cinese.",
    },
    {
        "pinyin": "Hěn lěng",
        "pronuncia": "hen leng",
        "significato": "Fa molto freddo",
        "esempio": "Per gli inverni di Pechino.",
    },
    {
        "pinyin": "Wǒ xiǎng nǐ",
        "pronuncia": "uò sciàng nii",
        "significato": "Mi manchi / Penso a te",
        "esempio": "Dolcissima da inviare in un messaggio.",
    },
    {
        "pinyin": "Nǐ zhēn piàoliang",
        "pronuncia": "nii gen piào-liang",
        "significato": "Sei davvero bellissima",
        "esempio": "Un complimento perfetto per Jewel.",
    },
    {
        "pinyin": "Nǐ zhēn shuài",
        "pronuncia": "nii gen sciuài",
        "significato": "Sei davvero bello",
        "esempio": "'Shuài' è il bello in stile carismatico.",
    },
    {
        "pinyin": "Nǐ hěn cōngming",
        "pronuncia": "nii hen tsong-ming",
        "significato": "Sei molto intelligente",
        "esempio": "Complimento sicuro.",
    },
    {
        "pinyin": "Jiā yóu!",
        "pronuncia": "già iòu",
        "significato": "Forza! / Dai che ce la fai!",
        "esempio": "Letteralmente: 'aggiungi olio (al motore)'.",
    },
    {
        "pinyin": "Méi wèntí",
        "pronuncia": "méi uen-tì",
        "significato": "Nessun problema",
        "esempio": "Risposta tipo 'no problem' all'italiana.",
    },
    {
        "pinyin": "Dāngrán",
        "pronuncia": "dang-ràn",
        "significato": "Certamente",
        "esempio": "Per confermare con sicurezza.",
    },
    {
        "pinyin": "Yěxǔ",
        "pronuncia": "iè-sciü",
        "significato": "Forse",
        "esempio": "Quando non sei ancora sicura.",
    },
    {
        "pinyin": "Wǒ bù zhīdào",
        "pronuncia": "uò bu gi-dao",
        "significato": "Non lo so",
        "esempio": "Frase salvavita universale.",
    },
    {
        "pinyin": "Yǒu yìsi",
        "pronuncia": "iòu i-si",
        "significato": "Interessante / Divertente",
        "esempio": "Letteralmente: 'ha significato'.",
    },
    {
        "pinyin": "Méi yìsi",
        "pronuncia": "méi i-si",
        "significato": "Noioso",
        "esempio": "Il contrario di 'yǒu yìsi'.",
    },
    {
        "pinyin": "Tài hǎo le!",
        "pronuncia": "tài hao le",
        "significato": "Fantastico!",
        "esempio": "Per esultare in modo naturale.",
    },
    {
        "pinyin": "Zhēn de ma?",
        "pronuncia": "gen de ma",
        "significato": "Davvero?",
        "esempio": "Per esprimere sorpresa.",
    },
    {
        "pinyin": "Wǒ tóng yì",
        "pronuncia": "uò tong i",
        "significato": "Sono d'accordo",
        "esempio": "In riunioni e discussioni.",
    },
    {
        "pinyin": "Wǒ bù tóngyì",
        "pronuncia": "uò bu tong-i",
        "significato": "Non sono d'accordo",
        "esempio": "Per dissentire educatamente.",
    },
    {
        "pinyin": "Qǐng wèn",
        "pronuncia": "cing uen",
        "significato": "Mi scusi (per chiedere qualcosa)",
        "esempio": "Letteralmente: 'per favore chiedo'.",
    },
    {
        "pinyin": "Wǒ jiā yǒu sān gè rén",
        "pronuncia": "uò già iòu san ghe ren",
        "significato": "La mia famiglia è composta da tre persone",
        "esempio": "Cambia il numero a piacere.",
    },
    {
        "pinyin": "Nǐ duō dà?",
        "pronuncia": "nii duo da",
        "significato": "Quanti anni hai?",
        "esempio": "Domanda comune, niente di scortese.",
    },
    {
        "pinyin": "Wǒ èrshí suì",
        "pronuncia": "uò èr-sci suéi",
        "significato": "Ho vent'anni",
        "esempio": "Cambia il numero secondo necessità.",
    },
    {
        "pinyin": "Shēngrì kuàilè",
        "pronuncia": "sceng-ri kuài-le",
        "significato": "Buon compleanno",
        "esempio": "Da dire con torta e candeline.",
    },
    {
        "pinyin": "Xīn nián kuàilè",
        "pronuncia": "scin nien kuài-le",
        "significato": "Buon anno nuovo",
        "esempio": "Per il Capodanno cinese o gregoriano.",
    },
    {
        "pinyin": "Zhù nǐ hǎo yùn",
        "pronuncia": "giù nii hao iuen",
        "significato": "Ti auguro buona fortuna",
        "esempio": "Prima di un esame o un colloquio.",
    },
    {
        "pinyin": "Wǒ àihào shì lǚyóu",
        "pronuncia": "uò ài-hao sci lü-iòu",
        "significato": "Il mio hobby è viaggiare",
        "esempio": "Sostituisci 'lǚyóu' con altro.",
    },
    {
        "pinyin": "Wǒ xǐhuan yīnyuè",
        "pronuncia": "uò sci-huan in-iuè",
        "significato": "Mi piace la musica",
        "esempio": "Si combina con tanti altri sostantivi.",
    },
    {
        "pinyin": "Wǒ huì",
        "pronuncia": "uò huéi",
        "significato": "So fare / Posso",
        "esempio": "Ad esempio 'wǒ huì shuō Yìdàlì yǔ' = parlo italiano.",
    },
    {
        "pinyin": "Wǒ bù huì",
        "pronuncia": "uò bu huéi",
        "significato": "Non so fare / Non posso",
        "esempio": "Forma negativa di 'huì'.",
    },
    {
        "pinyin": "Zài nǎr?",
        "pronuncia": "zai nar",
        "significato": "Dove?",
        "esempio": "Domanda fondamentale di posizione.",
    },
    {
        "pinyin": "Zhèlǐ",
        "pronuncia": "gè-li",
        "significato": "Qui",
        "esempio": "Posizione vicina a chi parla.",
    },
    {
        "pinyin": "Nàlǐ",
        "pronuncia": "nà-li",
        "significato": "Lì / Là",
        "esempio": "Posizione lontana.",
    },
    {
        "pinyin": "Yìdiǎn diǎn",
        "pronuncia": "i-dièn dièn",
        "significato": "Un pochino",
        "esempio": "'Wǒ huì yìdiǎn diǎn' = ne so un po'.",
    },
    {
        "pinyin": "Fēicháng hǎo",
        "pronuncia": "fei-ciang hao",
        "significato": "Estremamente bene",
        "esempio": "Più forte di 'hěn hǎo'.",
    },
    {
        "pinyin": "Bù xíng",
        "pronuncia": "bu scing",
        "significato": "Non va bene / Non si può",
        "esempio": "Per rifiutare con decisione.",
    },
    {
        "pinyin": "Kěyǐ",
        "pronuncia": "kè-i",
        "significato": "Si può / Va bene",
        "esempio": "Per concedere il permesso.",
    },
    {
        "pinyin": "Wǒ qù shàngbān",
        "pronuncia": "uò ciü sciang-ban",
        "significato": "Vado al lavoro",
        "esempio": "Letteralmente: 'vado a far turno'.",
    },
    {
        "pinyin": "Xiàbān le",
        "pronuncia": "scià-ban le",
        "significato": "Ho finito di lavorare",
        "esempio": "Letteralmente: 'turno finito'.",
    },
    {
        "pinyin": "Wǒ zài xuéxí Zhōngwén",
        "pronuncia": "uò zai sciué-sci gong-uen",
        "significato": "Sto studiando cinese",
        "esempio": "Esattamente quello che stai facendo!",
    },
    {
        "pinyin": "Hànyǔ hěn yǒu yìsi",
        "pronuncia": "han-iü hen iòu i-si",
        "significato": "Il cinese è molto interessante",
        "esempio": "Hànyǔ = lingua cinese.",
    },
    {
        "pinyin": "Bǐ rú shuō",
        "pronuncia": "bi ru sciuo",
        "significato": "Per esempio",
        "esempio": "Per introdurre un esempio.",
    },
    {
        "pinyin": "Yīqǐ qù ba",
        "pronuncia": "i-ci ciü ba",
        "significato": "Andiamoci insieme",
        "esempio": "Il '-ba' rende la frase un invito.",
    },
    {
        "pinyin": "Wǒ qǐng kè",
        "pronuncia": "uò cing kè",
        "significato": "Offro io",
        "esempio": "Modo gentile di pagare il conto.",
    },
    {
        "pinyin": "Gānbēi!",
        "pronuncia": "gan-bei",
        "significato": "Cin cin! (brindisi)",
        "esempio": "Letteralmente: 'bicchiere asciutto'.",
    },
    {
        "pinyin": "Wǒ chī bǎo le",
        "pronuncia": "uò ci bao le",
        "significato": "Sono sazio/a",
        "esempio": "Da dire dopo una bella mangiata.",
    },
    {
        "pinyin": "Hěn hǎo wán",
        "pronuncia": "hen hao uan",
        "significato": "È molto divertente",
        "esempio": "Per descrivere un'esperienza.",
    },
    {
        "pinyin": "Bié dānxīn",
        "pronuncia": "bié dan-scin",
        "significato": "Non preoccuparti",
        "esempio": "Frase rassicurante.",
    },
    {
        "pinyin": "Xiǎoxīn",
        "pronuncia": "sciào-scin",
        "significato": "Attento / Stai attento",
        "esempio": "Letteralmente: 'cuore piccolo'.",
    },
    {
        "pinyin": "Wǒ huí jiā le",
        "pronuncia": "uò huéi già le",
        "significato": "Torno a casa",
        "esempio": "Da dire quando esci dall'ufficio.",
    },
    {
        "pinyin": "Míngtiān jiàn",
        "pronuncia": "ming-tien gièn",
        "significato": "A domani",
        "esempio": "Saluto per il giorno dopo.",
    },
    {
        "pinyin": "Yíhuìr jiàn",
        "pronuncia": "i-huèr gièn",
        "significato": "A dopo",
        "esempio": "Quando vi rivedete a breve.",
    },
    {
        "pinyin": "Zhù nǐ yílù píng'ān",
        "pronuncia": "giù nii i-lù ping-an",
        "significato": "Buon viaggio",
        "esempio": "Letteralmente: 'tutto il viaggio in pace'.",
    },
    {
        "pinyin": "Nǐ shì wǒ de bǎobèi",
        "pronuncia": "nii sci uò de bao-bèi",
        "significato": "Sei il mio tesoro",
        "esempio": "Dolcissimo nomignolo cinese.",
    },
    {
        "pinyin": "Wǒ yǒngyuǎn ài nǐ",
        "pronuncia": "uò iong-iuèn ài nii",
        "significato": "Ti amerò per sempre",
        "esempio": "Versione 'forever' di 'wǒ ài nǐ'.",
    },
    {
        "pinyin": "Wǒmen yīqǐ",
        "pronuncia": "uò-men i-ci",
        "significato": "Noi insieme",
        "esempio": "Frase corta ma romantica.",
    },
    {
        "pinyin": "Zhēn de hěn shuǎng",
        "pronuncia": "gen de hen sciuàng",
        "significato": "È davvero fantastico (sensazione)",
        "esempio": "'Shuǎng' è un misto di gusto e libertà.",
    },
    {
        "pinyin": "Suíbiàn",
        "pronuncia": "suéi-bièn",
        "significato": "Come ti pare / Fai tu",
        "esempio": "Quando lasci scegliere all'altro.",
    },
    {
        "pinyin": "Wǒ zài lùshàng",
        "pronuncia": "uò zai lu-sciàng",
        "significato": "Sono per strada / Sto arrivando",
        "esempio": "Il classico messaggio quando sei in ritardo.",
    },
    {
        "pinyin": "Děng yíxià",
        "pronuncia": "deng i-scià",
        "significato": "Aspetta un attimo",
        "esempio": "Da dire al telefono o di persona.",
    },
    {
        "pinyin": "Mǎshàng",
        "pronuncia": "mà-sciàng",
        "significato": "Subito / Immediatamente",
        "esempio": "Letteralmente: 'a cavallo'.",
    },
    {
        "pinyin": "Wǒ hěn xìngfú",
        "pronuncia": "uò hen scìng-fu",
        "significato": "Sono felice (in senso profondo)",
        "esempio": "'Xìngfú' è la felicità duratura.",
    },
    {
        "pinyin": "Wǒ hěn kāixīn",
        "pronuncia": "uò hen kai-scin",
        "significato": "Sono contento/a",
        "esempio": "'Kāixīn' è la gioia quotidiana.",
    },
    {
        "pinyin": "Jiànkāng zuì zhòngyào",
        "pronuncia": "gièn-kang zuéi giong-iao",
        "significato": "La salute è la cosa più importante",
        "esempio": "Saggezza cinese da regalare.",
    },
    {
        "pinyin": "Mànmàn lái",
        "pronuncia": "man-man lai",
        "significato": "Vai con calma",
        "esempio": "Letteralmente: 'vieni lentamente'.",
    },
    {
        "pinyin": "Yǒu zhì zhě, shì jìng chéng",
        "pronuncia": "iòu gi gè, sci ging cèng",
        "significato": "Dove c'è volontà, c'è una via",
        "esempio": "Proverbio motivazionale classico.",
    },
]


def get_expression_for_day(day_index: int) -> dict:
    """Restituisce l'espressione del giorno ciclando sulla lista."""
    return EXPRESSIONS[day_index % len(EXPRESSIONS)]
